package com.rds.platform.web.itsmws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-10-24T17:26:09.160+08:00
 * Generated source version: 2.7.17
 * 
 */
@WebService(targetNamespace = "http://www.chinawiserv.com/onecenter", name = "ProductServices")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDataSource", targetNamespace = "http://www.chinawiserv.com/onecenter", className = "com.rds.platform.web.itsmws.GetDataSource")
    @WebMethod
    @ResponseWrapper(localName = "getDataSourceResponse", targetNamespace = "http://www.chinawiserv.com/onecenter", className = "com.rds.platform.web.itsmws.GetDataSourceResponse")
    public java.lang.String getDataSource(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "goCreateWorkOrder", targetNamespace = "http://www.chinawiserv.com/onecenter", className = "com.rds.platform.web.itsmws.GoCreateWorkOrder")
    @WebMethod
    @ResponseWrapper(localName = "goCreateWorkOrderResponse", targetNamespace = "http://www.chinawiserv.com/onecenter", className = "com.rds.platform.web.itsmws.GoCreateWorkOrderResponse")
    public java.lang.String goCreateWorkOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://www.chinawiserv.com/onecenter", className = "com.rds.platform.web.itsmws.GetProducts")
    @WebMethod
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://www.chinawiserv.com/onecenter", className = "com.rds.platform.web.itsmws.GetProductsResponse")
    public java.lang.String getProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "submitCreateWorkOrder", targetNamespace = "http://www.chinawiserv.com/onecenter", className = "com.rds.platform.web.itsmws.SubmitCreateWorkOrder")
    @WebMethod
    @ResponseWrapper(localName = "submitCreateWorkOrderResponse", targetNamespace = "http://www.chinawiserv.com/onecenter", className = "com.rds.platform.web.itsmws.SubmitCreateWorkOrderResponse")
    public java.lang.String submitCreateWorkOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
