
package com.rds.platform.web.itsmws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-10-24T17:26:09.088+08:00
 * Generated source version: 2.7.17
 * 
 */
public final class ProductServices_ProductServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.chinawiserv.com/onecenter", "ProductServiceImplService");

    private ProductServices_ProductServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProductServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProductServiceImplService ss = new ProductServiceImplService(wsdlURL, SERVICE_NAME);
        ProductServices port = ss.getProductServiceImplPort();  
        
        {
        System.out.println("Invoking getDataSource...");
        java.lang.String _getDataSource_arg0 = "";
        java.lang.String _getDataSource__return = port.getDataSource(_getDataSource_arg0);
        System.out.println("getDataSource.result=" + _getDataSource__return);


        }
        {
        System.out.println("Invoking goCreateWorkOrder...");
        java.lang.String _goCreateWorkOrder_arg0 = "";
        java.lang.String _goCreateWorkOrder__return = port.goCreateWorkOrder(_goCreateWorkOrder_arg0);
        System.out.println("goCreateWorkOrder.result=" + _goCreateWorkOrder__return);


        }
        {
        System.out.println("Invoking getProducts...");
        java.lang.String _getProducts_arg0 = "";
        java.lang.String _getProducts__return = port.getProducts(_getProducts_arg0);
        System.out.println("getProducts.result=" + _getProducts__return);


        }
        {
        System.out.println("Invoking submitCreateWorkOrder...");
        java.lang.String _submitCreateWorkOrder_arg0 = "";
        java.lang.String _submitCreateWorkOrder__return = port.submitCreateWorkOrder(_submitCreateWorkOrder_arg0);
        System.out.println("submitCreateWorkOrder.result=" + _submitCreateWorkOrder__return);


        }

        System.exit(0);
    }

}
