package com.rds.platform.web.itsmws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-10-24T17:26:09.175+08:00
 * Generated source version: 2.7.17
 * 
 */
@WebServiceClient(name = "ProductServiceImplService", 
                  wsdlLocation = "file:/D:/wsdl.wsdl",
                  targetNamespace = "http://www.chinawiserv.com/onecenter") 
public class ProductServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.chinawiserv.com/onecenter", "ProductServiceImplService");
    public final static QName ProductServiceImplPort = new QName("http://www.chinawiserv.com/onecenter", "ProductServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/wsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/wsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProductServices
     */
    @WebEndpoint(name = "ProductServiceImplPort")
    public ProductServices getProductServiceImplPort() {
        return super.getPort(ProductServiceImplPort, ProductServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductServices
     */
    @WebEndpoint(name = "ProductServiceImplPort")
    public ProductServices getProductServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ProductServiceImplPort, ProductServices.class, features);
    }

}
