package com.rds.platform.web.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-10-24T17:53:27.804+08:00
 * Generated source version: 2.7.17
 * 
 */
@WebServiceClient(name = "UserCtrlService", 
                  wsdlLocation = "file:/E:/net-wsdl.wsdl",
                  targetNamespace = "http://WangShuai.UserCtrl.org/") 
public class UserCtrlService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://WangShuai.UserCtrl.org/", "UserCtrlService");
    public final static QName UserCtrlServiceSoap = new QName("http://WangShuai.UserCtrl.org/", "UserCtrlServiceSoap");
    public final static QName UserCtrlServiceSoap12 = new QName("http://WangShuai.UserCtrl.org/", "UserCtrlServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/net-wsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserCtrlService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/net-wsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserCtrlService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserCtrlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserCtrlService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserCtrlService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserCtrlService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserCtrlService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserCtrlServiceSoap
     */
    @WebEndpoint(name = "UserCtrlServiceSoap")
    public UserCtrlServiceSoap getUserCtrlServiceSoap() {
        return super.getPort(UserCtrlServiceSoap, UserCtrlServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserCtrlServiceSoap
     */
    @WebEndpoint(name = "UserCtrlServiceSoap")
    public UserCtrlServiceSoap getUserCtrlServiceSoap(WebServiceFeature... features) {
        return super.getPort(UserCtrlServiceSoap, UserCtrlServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns UserCtrlServiceSoap
     */
    @WebEndpoint(name = "UserCtrlServiceSoap12")
    public UserCtrlServiceSoap getUserCtrlServiceSoap12() {
        return super.getPort(UserCtrlServiceSoap12, UserCtrlServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserCtrlServiceSoap
     */
    @WebEndpoint(name = "UserCtrlServiceSoap12")
    public UserCtrlServiceSoap getUserCtrlServiceSoap12(WebServiceFeature... features) {
        return super.getPort(UserCtrlServiceSoap12, UserCtrlServiceSoap.class, features);
    }

}
